### ISSUE TITLE
Tensor dependency?

### ISSUE THREAD

**Issue by crertel** [Qqwy/elixir_map_diff#15]
Hi! Out of curiosity, why does this depend on Tensor?

**Comment by Qqwy** [comment]
That is a great question! Thank you for noticing.

Looking back into the history, it seems that I added it during commit 30fdd7215959c4e966d45f5a551a708b4a2e63bf, probably while performing some manual testing to see how the library would perform with nested data structures to see if these were correct.

There is no reason for the Tensor dependency to exist. The change that added that dependency should not have been pushed. 
I'll remove it. :slightly_smiling_face:
